moviedetails/urls.py
from django.urls import path
from .views import MovieDetails, saved
app_name = "moviedetails"

urlpatterns = [
    path("", MovieDetails.as_view(), name="details"),
    path("saved", saved, name="saved"),
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("moviedetails.urls")),
    path('admin/', admin.site.urls),
]

moviedetails/models.py
from django.db import models

# Create your models here.
class Saved(models.Model):
    name = models.CharField(max_length=10000)
    

moviedetails/views.py
from django.shortcuts import render
from django.views import View
from .helper import apology, get_movie_data
from .models import Saved
# Create your views here.

class MovieDetails(View):
    def get(self, request):
        return render(request, "moviedetails/index.html")
    
    def post(self, request):
        q = request.POST.get("q").lower()
        data = get_movie_data(q)
        if data.get("Response") == "False":
            return apology(request, data.get("Error"))
        
        context = {
            "data": data,
        }
        try: 
            Saved.objects.get(name=q)
        except Exception:
            Saved.objects.create(name=q)    
        return render(request, "moviedetails/detail.html", context)
    
def saved(request):
    movies = []
    try:
        names = Saved.objects.all()
        for name in names:
            movies.append(get_movie_data(name.name))
    except Exception:
        movies = None
    
    context = {
        "movies": movies
    }
        
    return render(request, "moviedetails/saved.html", context)
    
        

moviedetails/templates/moviedetails/apology.html
{% extends "moviedetails/base.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
    <!-- https://memegen.link/ -->
    <img alt="{{ top }}" class="border img-fluid" src="http://memegen.link/custom/{{ top | urlencode }}/{{ bottom | urlencode }}.jpg?alt=https://i.imgur.com/CsCgN7Ll.png&width=400" title="{{ top }}">
{% endblock %}

moviedetails/templates/moviedetails/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'moviedetails/style.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light m-4" style="font-size: 1.3rem;>
            <a class="navbar-brand" href="#">Movies</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'moviedetails:details' %}" id="home">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'moviedetails:saved' %}" id="saved">Saved Movies</a>
               
              </div>
            </div>
          </nav>
          <div class="container-fluid m-4">
              {% block main %}
              {% endblock main %}
            </div>
    </body>
</html>

moviedetails/templates/moviedetails/detail.html
{% extends 'moviedetails/base.html' %}
{% block title %}
    Movie Details
{% endblock title %}
{% block main %}
    <h1 class="text-center">Title: {{ data.Title }}</h1>
    <img src="{{ data.Poster }}" alt="Poster" class="img-fluid rounded mx-auto d-block m-4">
    <div class="details" style="font-size: 1.3rem;">
        <p>
            <b>
                About movie:
            </b>
            {{ data.Plot }}
        </p>
        <p>
            <b>
                Liked By:
            </b>  
            {% if data.imdbVotes == "N/A" %}
                No
            {% else %}
                {{ data.imdbVotes }}
            {% endif %}
        </p>
        <p>
            <b>
                Release data:
            </b>
            {{ data.Released }}
        </p>
        <p>
            <b>
                Actors:
            </b> {{ data.Actors }}
        </p>
        <p>
            <b>Languages:</b> {{ data.Language }}
    </p>
    <p>
        <b>Genre</b> {{ data.Genre }}
</p>
</div>
<script>
    let home = document.querySelector("#home");
    console.log(home);
    home.classList.add("active");
</script>

{% endblock main %}

moviedetails/templates/moviedetails/index.html
{% extends 'moviedetails/base.html' %}
{% block title %}
    Search Movie
{% endblock title %}
{% block main %}
    <h1>Search Movies</h1>
    <form action="" method="post" class="form-inline mt-5">
        {% csrf_token %}
        <div class="form-group mb-2 mr-3">
            <input type="text" name="q" placeholder="Movie Name" class="form-control" autofocus>
          </div>
          <button type="submit" class="btn btn-primary mb-2">Search</button>
    </form>
    <script>
        let home = document.querySelector("#home");
        console.log(home);
        home.classList.add("active");
    </script>
    
{% endblock main %}

moviedetails/templates/moviedetails/saved.html
{% extends 'moviedetails/base.html' %}
{% block title %}
    Saved Movies
{% endblock title %}
{% block main %}
    <style>
    img:hover {
        cursor: pointer;
    }
    </style>
    <h1>Saved Movies</h1>
    {% for data in movies %}
        <h3>Title: {{ data.Title }}</h3>
        <form action="{% url 'moviedetails:details' %}"
              method="post"
              class="godetail">
            {% csrf_token %}
            <img src="{{ data.Poster }}"
                 alt="Movie Poster"
                 onclick="form.submit()"
                 class="my-4">
            <input type="hidden" name="q" value="{{ data.Title }}">
        </form>
        <p>
            {% if data.imdbVotes == "N/A" %}
                No
            {% else %}
                {{ data.imdbVotes }}
            {% endif %}
            <b> Likes </b>
        </p>
        <p>
            <b>
                Release data:
            </b>
            {{ data.Released }}
        </p>
        <p>
            <b>Genre: </b> {{ data.Genre }}
    </p>
    <hr>
{% endfor %}
<script>
    var forms = document.querySelectorAll(".godetail");
    images = document.querySelectorAll("img")
    console.log(forms);
    console.log(images);
    for (let i = 0; i < images.length; i++) {
        images[i].addEventListener("click", function() {
            console.log("he")
            forms[i].submit();})
    }
        let saved = document.querySelector("#saved");
        console.log(saved);
        saved.classList.add("active");
    
</script>
{% endblock main %}